### ISSUE TITLE
pod error

### ISSUE THREAD

**Issue by wyhazq** [lincode/FRDModuleManager#2]
日志：

Finding Podfile changes
  A Rexxar
  - AFNetworking
  - FRDIntent

Fetching external sources
-> Pre-downloading: `Rexxar` from `https://github.com/lincode/FRDModuleManager.git`, commit `0.1.0`
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/lincode/FRDModuleManager.git
     /var/folders/z7/qw_mkgz91831pvq5sq7s3t6h0000gn/T/d20161101-26507-1ijf228
     --template=
     Cloning into '/var/folders/z7/qw_mkgz91831pvq5sq7s3t6h0000gn/T/d20161101-26507-1ijf228'...
   $ /usr/bin/git checkout --quiet 0.1.0
   error: pathspec '0.1.0' did not match any file(s) known to git.

[!] Error installing Rexxar
[!] /usr/bin/git checkout --quiet 0.1.0

error: pathspec '0.1.0' did not match any file(s) known to git.

**Comment by guoshao-dev** [comment]
多谢，请将 pod 命令改为：

```
  pod 'FRDModuleManager', :git => 'https://github.com/lincode/FRDModuleManager.git', :commit => '0.1.0'
```

抱歉写错了 REAMDE。

**Comment by wyhazq** [comment]
成功了，谢谢，抱歉没能及时回复。
