### ISSUE TITLE
第一次见识到这种做法，很受启发啊

### ISSUE THREAD

**Issue by lyleLH** [lincode/FRDModuleManager#4]
1.注册过的对象会都变成和`AppDelegate`一样生命周期的单例对象吗？
2.是不是`TimelineModule`的实例其他业务功能不变，只是新增了`AppDelegate`生命周期的那些协议的方法的委托？

**Comment by guoshao-dev** [comment]
1.不是一定是单例对象，只是加到一个数组里了。
2.对的，只是把 AppDelegate 的生命周期调用分散到类似 TimelineModule 这样的模块里了。

**Comment by lyleLH** [comment]
OK  我再研究研究，感谢🙏
