### ISSUE TITLE
window初始化问题

### ISSUE THREAD

**Issue by iOSleep** [lincode/FRDModuleManager#5]
那还是应该在appdelegate中进行初始化的window么
比如说我又更换rootViewController的逻辑,  检测应用是否需要升级.

**Comment by guoshao-dev** [comment]
在 AppDelegate 中初始化。FRDModuleManager 这个工具只是用于分离原来需要写在 AppDelegate 中的业务模块代码。除非你有业务模块要配置 window。

**Comment by iOSleep** [comment]
好的~ 那可以抽取部分通知相关的内容么, 想单独把通知拿出来, 那就需要在manager中添加相关代理, 再在appdelegate中调用了吧~

**Comment by guoshao-dev** [comment]
可以只使用通知相关的钩子方法。
