### ISSUE TITLE
FRDTimelineModule和FRDGroupModule中，didFinishLaunchingWithOptions方法调用了两次

### ISSUE THREAD

**Issue by coderZhou10496** [lincode/FRDModuleManager#9]
运行了demo，发现FRDTimelineModule和FRDGroupModule两个类中didFinishLaunchingWithOptions方法都调用了两次，发现原因是AppDelegate里
- (BOOL)application:(UIApplication *)application willFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  NSString* plistPath = [[NSBundle mainBundle] pathForResource:@"ModulesRegister" ofType:@"plist"];
  FRDModuleManager *manager = [FRDModuleManager sharedInstance];
  [manager loadModulesWithPlistFile:plistPath];
  [manager application:application didFinishLaunchingWithOptions:launchOptions];
  return YES;
}
这个方法里，不应该是  [manager application:application willFinishLaunchingWithOptions:launchOptions]吗？

**Comment by guoshao-dev** [comment]
@coderZhou10496 

fix in https://github.com/lincode/FRDModuleManager/pull/10
